// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using legalcases.EntityModels;

#nullable disable

namespace SolicitorSync.Migrations
{
    [DbContext(typeof(LegalCasesContext))]
    partial class LegalCasesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("legalcases.EntityModels.Case", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("assigned_attorney")
                        .HasColumnType("TEXT");

                    b.Property<string>("case_description")
                        .HasColumnType("TEXT");

                    b.Property<string>("case_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("case_state")
                        .HasColumnType("TEXT");

                    b.Property<string>("case_type")
                        .HasColumnType("TEXT");

                    b.Property<string>("client_name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("court_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("documents")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Cases");
                });
#pragma warning restore 612, 618
        }
    }
}
