version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
        - '5433:5433'
    environment:
        - POSTGRES_USER=caseadmin 
        - POSTGRES_PASSWORD=admin1
        - POSTGRES_DB=cases
    