@Cases.Api_HostAddress = https://localhost:5002

### Create Case
POST {{Cases.Api_HostAddress}}/api/cases
Content-Type: application/json

{
  "case_name": "Sample Case",
  "client_name": "Wick the Grick",
  "case_type": "Domestic",
  "case_state": "Open",
  "case_description": "Neighboor dispute",
  "assigned_attorney": "John Doe",
  "court_date": "2025-03-04T00:00:00Z"
}

